---
language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7

env:
  global:
    - COVERAGE=1
    # Encrypted code climate CC_TEST_REPORTER_ID=
    # - secure: ''

services:
  - redis-server

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bin/rubocop
  - bin/rspec --format doc
  - bin/check-version

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

jobs:
  include:
    - stage: release
      rvm: 2.7
      script: skip
      deploy:
        provider: rubygems
        api_key:
          # Encrypted rubygems API key
          # secure: ''
        gem: faulty
        on:
          tags: true
          repo: ParentSquare/faulty
